### ISSUE TITLE
Using '.' as output_path misses creating executable

### ISSUE THREAD

**Issue by cemrehancavdar** [tusharsadhwani/packaged#18]
Hey,

I was giving a shot to packaged. I gave output_path input "." because i mostly trust defaults when i try a new tool. 
I understand it is stupid thing to give it a dot as input but there may be a default name and put it to cwd or it should warn.

script:
`packaged . 'pip install .' 'python app.py' .
`

**Comment by tusharsadhwani** [comment]
You're right, `.` as a path should not work.

In fact, any existing file or non-empty directory should not work.

Would erroring out with a proper message be a fine fix in this case?

**Comment by cemrehancavdar** [comment]
Yeah a meaningfull mesage could cover it, thanks

**Comment by tusharsadhwani** [comment]
This has been fixed in `v0.5.3`, can you confirm?

**Comment by cemrehancavdar** [comment]
I confirm :100: , thanks!
