### ISSUE TITLE
What is the extension of a self extracting archieves?

### ISSUE THREAD

**Issue by cemrehancavdar** [tusharsadhwani/packaged#19]
I have tried basic project of a example nicegui app. Packaged is as .bin extension and without any extension. Both of those would'nt open as app.
MacOS (Apple Silicon) Archieve Utility blocks them as unsupported format as shown in example. 
I could able to execture it by changing it to sh from bin.
This approach won't work for examples on the website. They throw permission errors.
Do I missing something?

<img width="408" alt="blocking" src="https://github.com/tusharsadhwani/packaged/assets/50503448/dec3a085-2c8b-47a6-b048-fa3a0a08ced3">

**Comment by tusharsadhwani** [comment]
You are right, to make the file double-clickable in MacOS, you'll need to keep the extension as `.sh`.

I'll look into what other extension is possible because `.sh` isn't the most accurate here.

**Comment by tusharsadhwani** [comment]
I've updated the examples downloaded from the website. They should now be executable by double clicking.
